dciciani-srl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_CONN_HOST') }}"
      user: "{{ env_var('ELT_DATABASE_USERNAME') }}"
      password: "{{ env_var('ELT_DATABASE_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('ELT_DATABASE_NAME') }}"
      schema: staging
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections